# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a96b5eaa75a6abb4e98857a91d5ecd158e5404e91bf7c1d0384a52b32855070a8611c56b9ff90f3eeb251ce6dafd73c47a2d9180c9ef0ebb0043e40e9c530acb

test:
  secret_key_base: ca8d24a97febe45e49e18738ab1c29b6e64790661bc3feaa4a4fa5a6fe0f8c3c91f73abcb12ab61e1535ae7ca055b8820989120d459ac28b308a4689e03cd874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
